"""Refresh derivable DATA embedded in any doc — not just whole-file generators.

The goal: keep info-carrying docs current. Some docs are wholly generated (STATS.md).
But most stale info is a DATA FIELD embedded in an otherwise hand-written doc — a coverage
badge in README, a "N capability skills" count in getting-started. Those numbers drift as
the code changes; the surrounding prose does not. This refreshes the fields in place,
across every doc, and leaves the prose untouched.

A field is defined by:
  - a compiled regex that locates it (with a capture group for the current value),
  - a compute() that derives the TRUE value from source (code, filesystem, metrics),
  - a render() that formats the true value back into the matched text.

Only fields whose true value is MECHANICALLY COMPUTABLE from source belong here. Prose
that carries meaning a human must write is never a field — this engine cannot and must not
rewrite it. It only corrects numbers/counts/badges that have a single right answer.

Safety: a field only updates when compute() returns a value AND it differs from what's in
the doc. Compute failures are swallowed (the doc keeps its current value — never blanked).
"""
from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path
from collections.abc import Callable

YOUK_ROOT = Path("/youk")


@dataclass
class DataField:
    name: str
    pattern: re.Pattern                     # must have exactly one capture group = the value
    compute: Callable[[Path], str | None]   # returns true value as string, or None to skip
    describe: str


# ── compute functions (derive truth from source) ───────────────────────────

def _count_mcp_tools(youk_root: Path) -> str | None:
    total = 0
    for rel in ("servers/core/src/server.py", "servers/code/src/server.py"):
        f = youk_root / rel
        if f.exists():
            total += f.read_text().count("@mcp.tool()")
    return str(total) if total else None


def _count_skills(youk_root: Path) -> str | None:
    skills_dir = youk_root / "skills"
    if not skills_dir.is_dir():
        return None
    n = sum(1 for p in skills_dir.iterdir() if p.is_dir() and (p / "SKILL.md").exists())
    return str(n) if n else None


def _health_coverage(youk_root: Path) -> str | None:
    """Read the health.py coverage number from the coverage badge state if present.
    Falls back to None (leave the doc's value) when it can't be computed offline."""
    # The badge value is regenerated by `make coverage-badge`; we read the last known
    # value from a state file if the project writes one, else skip (never guess).
    cov_file = youk_root / "state" / "coverage.json"
    if cov_file.exists():
        try:
            import json
            val = json.loads(cov_file.read_text()).get("health_py")
            if val is not None:
                return str(int(val))
        except Exception:
            return None
    return None


# ── field registry ─────────────────────────────────────────────────────────
# Each field: a pattern with ONE capture group (the current value in the doc), and the
# compute that yields the correct value. Add a field only when its truth is computable.

def _fields() -> list[DataField]:
    return [
        DataField(
            name="capability_skill_count",
            pattern=re.compile(r"(\d+) capability skills"),
            compute=_count_skills,
            describe="number of skills/*/SKILL.md",
        ),
        DataField(
            name="mcp_tool_count",
            pattern=re.compile(r"(\d+) MCP tools"),
            compute=_count_mcp_tools,
            describe="number of @mcp.tool() across servers",
        ),
        DataField(
            name="health_coverage_badge",
            pattern=re.compile(r"coverage-(\d+)%25"),
            compute=_health_coverage,
            describe="health.py coverage percentage in the README badge",
        ),
    ]


def refresh_doc_data(
    doc_paths: list[str],
    youk_root: Path = YOUK_ROOT,
    dry_run: bool = False,
) -> dict:
    """Refresh every known data field in each given doc, in place.

    doc_paths: doc filenames relative to youk_root.
    dry_run: report what WOULD change without writing.

    Returns {"updated": [{doc, field, old, new}], "unchanged": int, "errors": [...]}.
    """
    fields = _fields()
    updated: list[dict] = []
    unchanged = 0
    errors: list[dict] = []

    for rel in doc_paths:
        path = youk_root / rel
        if not path.exists() or path.suffix != ".md":
            continue
        try:
            text = path.read_text()
        except Exception as exc:
            errors.append({"doc": rel, "error": str(exc)})
            continue

        new_text = text
        for field in fields:
            for m in field.pattern.finditer(text):
                current = m.group(1)
                try:
                    truth = field.compute(youk_root)
                except Exception:
                    truth = None
                if truth is None or truth == current:
                    unchanged += 1
                    continue
                # Replace this specific occurrence (whole match, swapping the value).
                old_frag = m.group(0)
                new_frag = old_frag.replace(current, truth, 1)
                new_text = new_text.replace(old_frag, new_frag)
                updated.append({"doc": rel, "field": field.name, "old": current, "new": truth})

        if new_text != text and not dry_run:
            try:
                path.write_text(new_text)
            except Exception as exc:
                errors.append({"doc": rel, "error": str(exc)})

    return {"updated": updated, "unchanged": unchanged, "errors": errors}
