#!/usr/bin/env python3
"""
Generate .git/hooks/pre-commit from contracts.md action-type rules.

Reads contracts.md, extracts lines matching "always run X before commit/push",
and writes an executable pre-commit hook that enforces them.

Run from YOUK_ROOT:
    python scripts/generate_precommit_hook.py [--dry-run]
"""

import re
import sys
from pathlib import Path

YOUK_ROOT = Path(__file__).parent.parent
CONTRACTS_FILE = YOUK_ROOT / "knowledge" / "contracts.md"
HOOK_FILE = YOUK_ROOT / ".git" / "hooks" / "pre-commit"

# Pattern: "always run <command> before commit" or "always run <command> before committing"
_ACTION_PATTERN = re.compile(
    r"always run\s+`?([^`\n]+?)`?\s+before\s+commit(?:ting)?",
    re.IGNORECASE,
)

_HOOK_HEADER = """\
#!/bin/bash
# youk contract enforcement — pre-commit hook
# Auto-generated by scripts/generate_precommit_hook.py from contracts.md
# Regenerate with: python scripts/generate_precommit_hook.py

YOUK_ROOT="$(git rev-parse --show-toplevel)"
cd "$YOUK_ROOT"

echo "[youk] Running contract pre-commit checks..."
"""

_HOOK_FOOTER = """\
echo "[youk] Pre-commit contracts satisfied."
"""

_COMMAND_BLOCK = """\
{command} || {{
    echo '[youk BLOCKED] contract violated: {contract_text}'
    exit 1
}}
"""


def extract_action_contracts(contracts_path: Path) -> list[tuple[str, str]]:
    """Return list of (command, contract_text) from action-type contracts."""
    if not contracts_path.exists():
        print(f"[warn] contracts.md not found at {contracts_path} — using built-in defaults")
        return []

    results = []
    text = contracts_path.read_text()
    for match in _ACTION_PATTERN.finditer(text):
        command = match.group(1).strip()
        # Extract the full sentence as the contract text (up to line end)
        start = max(0, match.start() - 100)
        line_excerpt = text[start:match.end()].split("\n")[-1].strip()
        results.append((command, line_excerpt or f"always run {command} before commit"))
    return results


def _default_commands() -> list[tuple[str, str]]:
    return [
        ("ruff check servers/", "always run ruff check servers/ before committing"),
        (
            "python -m pytest tests/ -q --tb=no 2>/dev/null",
            "always run full pytest suite before committing",
        ),
        # Personal-data gate: block a commit that would ship a known identifier (the git
        # author's name, or an email) into a committed file. Prevention, not just detection —
        # the leak never enters history. Exits non-zero (blocks) when scan_for_precommit finds one.
        (
            "python -c \"import sys; sys.path.insert(0,'servers/core/src'); "
            "from pathlib import Path; from personal_data_pulse import scan_for_precommit; "
            "r=scan_for_precommit(Path('.')); "
            "[print('  LEAK', l['file']+':'+str(l['line_no']), l['kind'], repr(l['hit'])) for l in r['leaks']]; "
            "sys.exit(1 if r['blocked'] else 0)\"",
            "never commit personal data (names/emails) into shipped files — keep it local",
        ),
        # Note: voice gate (check_text on commit messages) runs in the commit-msg hook,
        # not here. commit-msg fires after COMMIT_EDITMSG is written; pre-commit fires before.
        # See generate_commitmsg_hook.py or the commit-msg hook for that gate.
    ]


def generate_hook(contracts_path: Path) -> str:
    extracted = extract_action_contracts(contracts_path)

    # Deduplicate by full command string
    seen: set[str] = set()
    commands: list[tuple[str, str]] = []
    for cmd, text in (extracted or _default_commands()):
        if cmd not in seen:
            seen.add(cmd)
            commands.append((cmd, text))

    blocks = [_HOOK_HEADER]
    for cmd, contract_text in commands:
        blocks.append(_COMMAND_BLOCK.format(command=cmd, contract_text=contract_text))
    blocks.append(_HOOK_FOOTER)
    return "\n".join(blocks)


def main() -> None:
    dry_run = "--dry-run" in sys.argv
    hook_content = generate_hook(CONTRACTS_FILE)

    if dry_run:
        print("--- DRY RUN ---")
        print(hook_content)
        return

    HOOK_FILE.write_text(hook_content)
    HOOK_FILE.chmod(0o755)
    print(f"[youk] Pre-commit hook written to {HOOK_FILE}")
    print(f"       Commands enforced: {hook_content.count('BLOCKED')}")


if __name__ == "__main__":
    main()
