#!/usr/bin/env python3
"""Generate .git/hooks/commit-msg for voice gate enforcement.

commit-msg fires after COMMIT_EDITMSG is written (unlike pre-commit which fires
before). This is the correct hook for checking the commit message content.

Run from YOUK_ROOT:
    python scripts/generate_commitmsg_hook.py [--dry-run]
"""
import sys
from pathlib import Path

YOUK_ROOT = Path(__file__).parent.parent
HOOK_FILE = YOUK_ROOT / ".git" / "hooks" / "commit-msg"

_HOOK = """\
#!/bin/bash
# youk commit-msg hook — voice gate on commit messages
# Auto-generated by scripts/generate_commitmsg_hook.py
# Regenerate with: python scripts/generate_commitmsg_hook.py

YOUK_ROOT="$(git rev-parse --show-toplevel)"
cd "$YOUK_ROOT"
python scripts/voice_gate_precommit.py || exit 1
"""


def main() -> None:
    dry_run = "--dry-run" in sys.argv
    if dry_run:
        print("--- DRY RUN ---")
        print(_HOOK)
        return
    HOOK_FILE.write_text(_HOOK)
    HOOK_FILE.chmod(0o755)
    print(f"[youk] commit-msg hook written to {HOOK_FILE}")


if __name__ == "__main__":
    main()
