#!/usr/bin/env python3
"""Generate .git/hooks/commit-msg for voice gate enforcement.

commit-msg fires after COMMIT_EDITMSG is written (unlike pre-commit which fires
before). This is the correct hook for checking the commit message content.

Run from YOUK_ROOT:
    python scripts/generate_commitmsg_hook.py [--dry-run]
"""
import sys
from pathlib import Path

YOUK_ROOT = Path(__file__).parent.parent
# --git-common-dir so a worktree installs into the shared hooks directory rather
# than a .git file path that cannot hold one.
def _hooks_dir() -> Path:
    import subprocess
    try:
        out = subprocess.run(["git", "rev-parse", "--git-common-dir"],
                             capture_output=True, text=True, timeout=5,
                             cwd=str(YOUK_ROOT))
        if out.returncode == 0:
            d = Path(out.stdout.strip())
            if not d.is_absolute():
                d = YOUK_ROOT / d
            return d / "hooks"
    except Exception:
        pass
    return YOUK_ROOT / ".git" / "hooks"


HOOK_FILE = _hooks_dir() / "commit-msg"

_HOOK = """\
#!/bin/bash
# youk commit-msg hook — voice gate on commit messages
# Auto-generated by scripts/generate_commitmsg_hook.py
# Regenerate with: python scripts/generate_commitmsg_hook.py

YOUK_ROOT="$(git rev-parse --show-toplevel)"
cd "$YOUK_ROOT"
# "$1" is the commit message file git passes to a commit-msg hook. Forwarding it is
# what lets the gate work in a worktree, where .git is a file and the old guessed
# path did not exist, so the gate exited 0 on every commit.
python3 scripts/voice_gate_precommit.py "$1" || exit 1
"""


def main() -> None:
    dry_run = "--dry-run" in sys.argv
    if dry_run:
        print("--- DRY RUN ---")
        print(_HOOK)
        return
    HOOK_FILE.write_text(_HOOK)
    HOOK_FILE.chmod(0o755)
    print(f"[youk] commit-msg hook written to {HOOK_FILE}")


if __name__ == "__main__":
    main()
