#!/usr/bin/env python3
"""Pre-commit voice gate — blocks commits with hard AI-tells in the message.

Called by the pre-commit hook generated by generate_precommit_hook.py.
Reads .git/COMMIT_EDITMSG, runs check_text, exits 1 on BLOCKED.
Silent-exits 0 if voice_fingerprint is not importable (gate absent).
"""
import pathlib
import sys

root = pathlib.Path(__file__).parent.parent
sys.path.insert(0, str(root / "servers" / "core" / "src"))

try:
    from voice_fingerprint import check_text
except ImportError:
    sys.exit(0)

msg_path = root / ".git" / "COMMIT_EDITMSG"
if not msg_path.exists():
    sys.exit(0)

msg = "\n".join(
    l for l in msg_path.read_text(encoding="utf-8", errors="replace").splitlines()
    if not l.startswith("#")
).strip()
if not msg:
    sys.exit(0)

result = check_text(msg)
if result["gate"] == "BLOCKED":
    print("[youk BLOCKED] Voice gate: commit message has hard AI-tells:")
    for t in result["tells_hard"]:
        print(f"  {t}")
    print("Rewrite and retry.")
    sys.exit(1)
elif result["gate"] == "REVIEW":
    print("[youk REVIEW] Voice gate: commit message has soft AI-tells (not blocking):")
    for t in result["tells_soft"]:
        print(f"  {t}")
